"""empty message

Revision ID: 70944e980ea5
Revises: 
Create Date: 2021-04-22 10:25:24.487779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70944e980ea5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('category', sa.String(), nullable=True))
    op.add_column('meals', sa.Column('subcategory', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meals', 'subcategory')
    op.drop_column('meals', 'category')
    # ### end Alembic commands ###
